name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install Dependencies
      run: |
        composer install --optimize-autoloader --prefer-dist --no-dev --no-interaction -no-scripts
        composer global require "laravel/envoy"
    - name: Setup Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
        check-latest: true
    - name: Install NPM dependencies
      run: npm install
    - name: Compile assets for production
      run: npm run production
    - name: Run Envoy deploy
      run: envoy run deploy
